# Generated by Django 4.1.3 on 2023-06-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenseapp", "0002_remove_expense_user_alter_expense_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=250)),
                ("email_id", models.EmailField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("food", "Food"),
                    ("transportation", "Transportation"),
                    ("utilities", "Utilities"),
                    ("other", "Other"),
                ],
                max_length=250,
            ),
        ),
    ]
